-- DRIVE UTILIZADO É O SQLITE

CREATE TABLE IF NOT EXISTS PESSOAS (
    PESSOAID INTEGER NOT NULL PRIMARY KEY  AUTOINCREMENT,

    NOME VARCHAR (50),
    DT_NASCIMENTO DATE,
    SEXO CHAR,
    CPF VARCHAR (11),
    TIPO CHAR 
);

CREATE TABLE IF NOT EXISTS VACINAS (
    VACINASID INTEGER NOT NULL PRIMARY KEY  AUTOINCREMENT,
    NOME_VACINDA VARCHAR(50),
    NOME_PESQUISADOR_RESP VARCHAR(50),
    PAIS_ORIGEM VARCHAR(30),
    EST_PESQUISA VARCHAR(20),
    DT_INICIO_PESQUISA DATE
);